import { TabContentItem } from '../tab-navigation-base/tab-content-item';
import { TabStripItem } from '../tab-navigation-base/tab-strip-item';
import { TextTransform } from '../text-base';
import { Color } from '../../color';
import { Font } from '../styling/font';
import { TabNavigationBase } from '../tab-navigation-base/tab-navigation-base';
export declare const tabs: WeakRef<BottomNavigation>[];
export declare class BottomNavigation extends TabNavigationBase {
    private _contentView;
    private _contentViewId;
    private _bottomNavigationBar;
    private _currentFragment;
    private _currentTransaction;
    private _attachedToWindow;
    _originalBackground: any;
    private _textTransform;
    private _selectedItemColor;
    private _unSelectedItemColor;
    constructor();
    get _hasFragments(): boolean;
    onItemsChanged(oldItems: TabContentItem[], newItems: TabContentItem[]): void;
    createNativeView(): org.nativescript.widgets.GridLayout;
    initNativeView(): void;
    _loadUnloadTabItems(newIndex: number): void;
    onLoaded(): void;
    _onAttachedToWindow(): void;
    _onDetachedFromWindow(): void;
    onUnloaded(): void;
    disposeNativeView(): void;
    _onRootViewReset(): void;
    private disposeTabFragments;
    private get currentTransaction();
    private commitCurrentTransaction;
    changeTab(index: number): void;
    private instantiateItem;
    private setPrimaryItem;
    private destroyItem;
    private setTabStripItems;
    private getItemLabelTextTransform;
    private createTabItemSpec;
    private getOriginalIcon;
    private getDrawableInfo;
    private getIconInfo;
    private getFixedSizeIcon;
    updateAndroidItemAt(index: number, spec: org.nativescript.widgets.TabItemSpec): void;
    getTabBarBackgroundColor(): android.graphics.drawable.Drawable;
    setTabBarBackgroundColor(value: android.graphics.drawable.Drawable | Color): void;
    private updateTabStripItems;
    _setItemsColors(items: Array<TabStripItem>): void;
    getTabBarSelectedItemColor(): Color;
    setTabBarSelectedItemColor(value: Color): void;
    getTabBarUnSelectedItemColor(): Color;
    setTabBarUnSelectedItemColor(value: Color): void;
    private updateItem;
    setTabBarItemTitle(tabStripItem: TabStripItem, value: string): void;
    setTabBarItemBackgroundColor(tabStripItem: TabStripItem, value: android.graphics.drawable.Drawable | Color): void;
    _setItemColor(tabStripItem: TabStripItem): void;
    private setIconColor;
    setTabBarItemColor(tabStripItem: TabStripItem, value: number | Color): void;
    setTabBarIconColor(tabStripItem: TabStripItem, value: number | Color): void;
    setTabBarIconSource(tabStripItem: TabStripItem, value: number | Color): void;
    setTabBarItemFontInternal(tabStripItem: TabStripItem, value: Font): void;
    setTabBarItemTextTransform(tabStripItem: TabStripItem, value: TextTransform): void;
    getTabBarTextTransform(): TextTransform;
    setTabBarTextTransform(value: TextTransform): void;
}
