import { Style as StyleDefinition } from '.';
import { Color } from '../../../color';
import { Font, FontStyle, FontWeight } from '../font';
import { Background } from '../background';
import { dip } from '../../core/view';
import { ViewBase } from '../../core/view-base';
import { Length, PercentLength, HorizontalAlignment, VerticalAlignment, BackgroundRepeat, Visibility } from '../../styling/style-properties';
import { LinearGradient } from '../../styling/linear-gradient';
import { Observable } from '../../../data/observable';
import { FlexDirection, FlexWrap, JustifyContent, AlignItems, AlignContent, Order, FlexGrow, FlexShrink, FlexWrapBefore, AlignSelf } from '../../layouts/flexbox-layout';
import { TextAlignment, TextDecoration, TextTransform, WhiteSpace } from '../../text-base';
export interface CommonLayoutParams {
    width: number;
    height: number;
    widthPercent: number;
    heightPercent: number;
    leftMargin: number;
    topMargin: number;
    rightMargin: number;
    bottomMargin: number;
    leftMarginPercent: number;
    topMarginPercent: number;
    rightMarginPercent: number;
    bottomMarginPercent: number;
    horizontalAlignment: HorizontalAlignment;
    verticalAlignment: VerticalAlignment;
}
export declare class Style extends Observable implements StyleDefinition {
    private unscopedCssVariables;
    private scopedCssVariables;
    constructor(ownerView: ViewBase | WeakRef<ViewBase>);
    setScopedCssVariable(varName: string, value: string): void;
    setUnscopedCssVariable(varName: string, value: string): void;
    getCssVariable(varName: string): string | null;
    resetScopedCssVariables(): void;
    resetUnscopedCssVariables(): void;
    toString(): string;
    fontInternal: Font;
    backgroundInternal: Background;
    rotate: number;
    rotateX: number;
    rotateY: number;
    perspective: number;
    scaleX: number;
    scaleY: number;
    translateX: dip;
    translateY: dip;
    clipPath: string;
    color: Color;
    tintColor: Color;
    placeholderColor: Color;
    background: string;
    backgroundColor: Color;
    backgroundImage: string | LinearGradient;
    backgroundRepeat: BackgroundRepeat;
    backgroundSize: string;
    backgroundPosition: string;
    borderColor: string | Color;
    borderTopColor: Color;
    borderRightColor: Color;
    borderBottomColor: Color;
    borderLeftColor: Color;
    borderWidth: string | Length;
    borderTopWidth: Length;
    borderRightWidth: Length;
    borderBottomWidth: Length;
    borderLeftWidth: Length;
    borderRadius: string | Length;
    borderTopLeftRadius: Length;
    borderTopRightRadius: Length;
    borderBottomRightRadius: Length;
    borderBottomLeftRadius: Length;
    fontSize: number;
    fontFamily: string;
    fontStyle: FontStyle;
    fontWeight: FontWeight;
    font: string;
    androidElevation: number;
    androidDynamicElevationOffset: number;
    zIndex: number;
    opacity: number;
    visibility: Visibility;
    letterSpacing: number;
    lineHeight: number;
    textAlignment: TextAlignment;
    textDecoration: TextDecoration;
    textTransform: TextTransform;
    whiteSpace: WhiteSpace;
    minWidth: Length;
    minHeight: Length;
    width: PercentLength;
    height: PercentLength;
    margin: string | PercentLength;
    marginLeft: PercentLength;
    marginTop: PercentLength;
    marginRight: PercentLength;
    marginBottom: PercentLength;
    padding: string | Length;
    paddingLeft: Length;
    paddingTop: Length;
    paddingRight: Length;
    paddingBottom: Length;
    horizontalAlignment: HorizontalAlignment;
    verticalAlignment: VerticalAlignment;
    tabTextFontSize: number;
    tabTextColor: Color;
    tabBackgroundColor: Color;
    selectedTabTextColor: Color;
    androidSelectedTabHighlightColor: Color;
    separatorColor: Color;
    selectedBackgroundColor: Color;
    statusBarStyle: 'light' | 'dark';
    androidStatusBarBackground: Color;
    androidContentInset: string | Length;
    androidContentInsetLeft: Length;
    androidContentInsetRight: Length;
    flexDirection: FlexDirection;
    flexWrap: FlexWrap;
    justifyContent: JustifyContent;
    alignItems: AlignItems;
    alignContent: AlignContent;
    order: Order;
    flexGrow: FlexGrow;
    flexShrink: FlexShrink;
    flexWrapBefore: FlexWrapBefore;
    alignSelf: AlignSelf;
    PropertyBag: {
        new (): {
            [property: string]: string;
        };
        prototype: {
            [property: string]: string;
        };
    };
    viewRef: WeakRef<ViewBase>;
    get view(): ViewBase;
}
