import { TabContentItem } from '../tab-navigation-base/tab-content-item';
import { TabStripItem } from '../tab-navigation-base/tab-strip-item';
import { TextTransform } from '../text-base';
import { Color } from '../../color';
import { Font } from '../styling/font';
import { TabsBase } from './tabs-common';
export * from './tabs-common';
export declare const tabs: WeakRef<Tabs>[];
export declare class Tabs extends TabsBase {
    private _tabsBar;
    private _viewPager;
    private _pagerAdapter;
    private _androidViewId;
    _originalBackground: any;
    private _textTransform;
    private _selectedItemColor;
    private _unSelectedItemColor;
    animationEnabled: boolean;
    constructor();
    get _hasFragments(): boolean;
    onItemsChanged(oldItems: TabContentItem[], newItems: TabContentItem[]): void;
    createNativeView(): org.nativescript.widgets.GridLayout;
    initNativeView(): void;
    _loadUnloadTabItems(newIndex: number): void;
    onLoaded(): void;
    onUnloaded(): void;
    disposeNativeView(): void;
    _onRootViewReset(): void;
    private disposeCurrentFragments;
    private shouldUpdateAdapter;
    private setItems;
    private setTabStripItems;
    private getItemLabelTextTransform;
    private createTabItemSpec;
    private getIcon;
    private getFixedSizeIcon;
    updateAndroidItemAt(index: number, spec: org.nativescript.widgets.TabItemSpec): void;
    getTabBarBackgroundColor(): android.graphics.drawable.Drawable;
    setTabBarBackgroundColor(value: android.graphics.drawable.Drawable | Color): void;
    private updateTabStripItems;
    getTabBarHighlightColor(): number;
    setTabBarHighlightColor(value: number | Color): void;
    private setItemsColors;
    getTabBarSelectedItemColor(): Color;
    setTabBarSelectedItemColor(value: Color): void;
    getTabBarUnSelectedItemColor(): Color;
    setTabBarUnSelectedItemColor(value: Color): void;
    private updateItem;
    setTabBarItemTitle(tabStripItem: TabStripItem, value: string): void;
    setTabBarItemBackgroundColor(tabStripItem: TabStripItem, value: android.graphics.drawable.Drawable | Color): void;
    _setItemColor(tabStripItem: TabStripItem): void;
    private setIconColor;
    setTabBarItemColor(tabStripItem: TabStripItem, value: number | Color): void;
    setTabBarIconColor(tabStripItem: TabStripItem, value: number | Color): void;
    setTabBarIconSource(tabStripItem: TabStripItem, value: number | Color): void;
    setTabBarItemFontInternal(tabStripItem: TabStripItem, value: Font): void;
    getTabBarItemTextTransform(tabStripItem: TabStripItem): TextTransform;
    setTabBarItemTextTransform(tabStripItem: TabStripItem, value: TextTransform): void;
    getTabBarTextTransform(): TextTransform;
    setTabBarTextTransform(value: TextTransform): void;
}
