import { LayoutBase as LayoutBaseDefinition } from './layout-base';
import { View, CustomLayoutView, AddChildFromBuilder } from '../core/view';
import { Property } from '../core/properties';
import { Length } from '../styling/style-properties';
export declare class LayoutBaseCommon extends CustomLayoutView implements LayoutBaseDefinition, AddChildFromBuilder {
    private _subViews;
    _addChildFromBuilder(name: string, value: any): void;
    getChildrenCount(): number;
    get _childrenCount(): number;
    getChildAt(index: number): View;
    getChildIndex(child: View): number;
    getChildById(id: string): import("../core/view-base").ViewBase;
    _registerLayoutChild(child: View): void;
    _unregisterLayoutChild(child: View): void;
    addChild(child: View): void;
    insertChild(child: View, atIndex: number): void;
    removeChild(child: View): void;
    removeChildren(): void;
    get padding(): string | Length;
    set padding(value: string | Length);
    get paddingTop(): Length;
    set paddingTop(value: Length);
    get paddingRight(): Length;
    set paddingRight(value: Length);
    get paddingBottom(): Length;
    set paddingBottom(value: Length);
    get paddingLeft(): Length;
    set paddingLeft(value: Length);
    clipToBounds: boolean;
    isPassThroughParentEnabled: boolean;
    _childIndexToNativeChildIndex(index?: number): number;
    eachChildView(callback: (child: View) => boolean): void;
    eachLayoutChild(callback: (child: View, isLast: boolean) => void): void;
}
export declare const clipToBoundsProperty: Property<LayoutBaseCommon, boolean>;
export declare const isPassThroughParentEnabledProperty: Property<LayoutBaseCommon, boolean>;
